packages:
  - web
minimumReleaseAge: 4320 # 3 days
trustPolicy: "no-downgrade"
blockExoticSubdeps: true
allowBuilds:
  "@astrojs/compiler-rs": true
  "@biomejs/biome": true
  esbuild: true
  sharp: true
  workerd: true
overrides:
  chokidar: "^5.0.0"
  semver: "^7.0.0"
