packages:
  - web
  - app
savePrefix: ""
minimumReleaseAge: 4320 # 3 days
blockExoticSubdeps: true
allowBuilds:
  "@astrojs/compiler-rs": true
  "@biomejs/biome": true
  esbuild: true
  lefthook: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  # Renovate security update: pnpm@11.8.0
  - pnpm@11.8.0
  # Renovate security update: astro@7.1.0
  - astro@7.1.0
