export const ElementId = {
	CellTooltip: "cell-tooltip",
	ContactEmail: "contact-email",
	ContactEmailError: "contact-email-error",
	ContactForm: "contact-form",
	ContactMessage: "contact-message",
	ContactMessageError: "contact-message-error",
	ContactName: "contact-name",
	ContactNameError: "contact-name-error",
	ContactStatus: "contact-status",
	ContactSubmit: "contact-submit",
	ContactWebsite: "contact-website",
	CustomGrid: "custom-grid-container",
	CustomizerSection: "custom",
	CustomPaletteLabel: "custom-palette-label",
	CustomShapeLabel: "custom-shape-label",
	ErrorTitle: "error-title",
	ExportPreview: "export-preview",
	ExportSection: "export",
	ExportTabs: "export-tabs",
	HeroError: "hero-error",
	HeroGrid: "hero-grid-container",
	HeroRenderButton: "hero-render-btn",
	HeroRenderLabel: "hero-render-label",
	HeroUsername: "hero-username",
	HeroUsernameDisplay: "hero-username-display",
	HeroYear: "hero-year",
	HeroYearRange: "hero-year-range",
	HomeScreenWidgetSection: "widget",
	HowItWorksSection: "how",
	HowItWorksUsername: "how-it-works-username",
	MainContent: "main-content",
	PaletteList: "palette-list",
	PhoneScreen: "phone-screen",
	ShapeList: "shape-list",
	ThemeToggle: "theme-toggle",
	UsernameForm: "username-form",
	WidgetMiniGrid: "widget-mini-grid",
	WidgetUsername: "widget-username",
} as const;

export type ElementId = (typeof ElementId)[keyof typeof ElementId];

export const ClassName = {
	Active: "active",
	BarTag: "bar-tag",
	CodePreview: "code-preview",
	CopyButton: "copy-btn",
	DangerTone: "is-danger",
	ErrorEyebrow: "error-eyebrow",
	ErrorPage: "error-page",
	ErrorTerminal: "error-terminal",
	Footer: "footer",
	Hero: "hero",
	Legend: "legend",
	LegendSquare: "legend-sq",
	LegendStats: "legend-stats",
	PaletteRow: "palette-row",
	PngPreview: "png-preview",
	PreviewCard: "preview-card",
	PreviewChecker: "preview-checker",
	PreviewContent: "preview-content",
	PreviewTag: "preview-tag",
	Selected: "selected",
	Separator: "sep",
	ShapeButton: "shape-btn",
	SkipLink: "skip-link",
	SuggestionButton: "sug-btn",
} as const;

export const ThemeClass = {
	Light: "theme-light",
	Dark: "theme-dark",
} as const;

export const Selector = {
	PaletteRows: `#${ElementId.PaletteList} .${ClassName.PaletteRow}`,
	ShapeButtons: `#${ElementId.ShapeList} .${ClassName.ShapeButton}`,
	ActivePaletteRow: `#${ElementId.PaletteList} .${ClassName.PaletteRow}.${ClassName.Active}`,
	ActiveShapeButton: `#${ElementId.ShapeList} .${ClassName.ShapeButton}.${ClassName.Active}`,
	SelectedExportTab: `#${ElementId.ExportTabs} [aria-selected="true"]`,
	ExportTabKeys: `#${ElementId.ExportTabs} [data-key]`,
	ExportCodePreview: `#${ElementId.ExportPreview} .${ClassName.CodePreview}`,
	ExportCopyButton: `#${ElementId.ExportPreview} .${ClassName.CopyButton}`,
	ExportPngPreview: `#${ElementId.ExportPreview} .${ClassName.PngPreview}`,
	BarTag: `.${ClassName.BarTag}`,
	LegendSquares: `.${ClassName.Legend} .${ClassName.LegendSquare}`,
	LegendStats: `.${ClassName.LegendStats}`,
	SuggestionButtons: `.${ClassName.SuggestionButton}`,
} as const;
