name: 'Prepare Web Environment'
description: 'Sets up Node.js and pnpm for the web project'
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version-file: web/.nvmrc
        cache: pnpm
        cache-dependency-path: web/pnpm-lock.yaml
