name: CI Web

on:
  push:
    branches: [main]
    paths:
      - "web/**"
      - ".github/workflows/ci-web.yml"
      - ".github/actions/prepare-web-env/**"
  pull_request:
    branches: [main]
    paths:
      - "web/**"
      - ".github/workflows/ci-web.yml"
      - ".github/actions/prepare-web-env/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-check:
    name: Check (Web)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./.github/actions/prepare-web-env

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint:all

      - name: Type check
        run: pnpm lint:astro

      - name: Test
        run: pnpm test

  web-build:
    name: Build (Web)
    runs-on: ubuntu-latest
    needs: [web-check]
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./.github/actions/prepare-web-env

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm exec astro build
