name = "contribkit"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2026-01-01"

[assets]
directory = "dist"
binding = "ASSETS"

[[routes]]
pattern = "contribkit.app/*"
zone_name = "contribkit.app"

[[routes]]
pattern = "contribkit.app"
custom_domain = true
